name: Tests

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env file
        run: cp .env.ci .env

      - name: Run composer
        run: |
          composer install --no-interaction

      - name: Generate key
        run: |
          php artisan key:generate

      - name: Migrate database
        run: php artisan migrate --env=testing --force

      - name: Seed database
        run: php artisan db:seed --env=testing --force

      - name: Run test suite
        run: |
          php artisan test
